Feature/cft 3095 validate user permissions
keboola/python-cdc-component pull request #97
Opened 2024-09-20 10:23 UTC by kudj

2024-09-25 14:00 UTC, kudj commented
@davidesner validaci databas settings: 
```
**❌ Database Setup**
  - Binary logs are not enabled
  - `binlog_format` must be set to `ROW` or `row`
  - Binlog `binlog_row_image` must be set to `FUll` or `full`
``` 
mám přidat do validate_user_parmissions nebo udělat další metodu která bude volaná z test_connection? mám ji dát do db_common, nebo pouze do MySQL?

2024-09-25 14:15 UTC, davidesner commented
> @davidesner validaci databas settings:
> 
> ```
> **❌ Database Setup**
>   - Binary logs are not enabled
>   - `binlog_format` must be set to `ROW` or `row`
>   - Binlog `binlog_row_image` must be set to `FUll` or `full`
> ```
> 
> mám přidat do validate_user_parmissions nebo udělat další metodu která bude volaná z test_connection? mám ji dát do db_common, nebo pouze do MySQL?

Ja bych ji nahradil tu test_has_replication_privilege, ktera je vlastne stejne redundantni. a prejmenoval ji na test db setup, nebo neco takovyho. Urcite v common

2024-09-26 13:56 UTC, SgtMarmite commented on db_components/db_common/cdc_component.py
> +    def test_connection(self) -> ValidationResult:
Nebylo by lepší pojmenovat tohle jinak, než tu metodu v klientovi? + sync akce je validate_connection
Je to takhle zbytečně matoucí.

2024-09-26 14:02 UTC, SgtMarmite commented
Za mě je to v pohodě, až na ten naming. Nekontroloval jsem ale, jestli ty queries na práva správně.

2024-09-27 05:14 UTC, davidesner requested changes
Nechal jsem inline commenty. A nepovedlo se mi to otestovat vubec v KBC tam to konci App error. Zkousel jsi to testovat?

2024-09-27 05:14 UTC, davidesner commented on db_components/db_common/cdc_component.py
> +            if test_connection_result.get('missing_required'):
Co kdyz chybi i optional nebo db settings? Kdyz tohle vidim, tak by asi bylo lepsi vyhodit vlastni exception treba `TestConnection` exception, ktera bude obsahovat jak postavenou message, takze to muze rovnou probublat dolu a tady ten kod vubec nebude muset byt. A zaroven bude obsahovat detail, tj ten result json na ktery pak muzes sahnout uvnitr validate_connection sync akce

2024-09-27 05:14 UTC, davidesner commented on db_components/db_common/cdc_component.py
>          with self._init_client():
Co se stane kdyz jsou neplatny credentials? Vypada to, ze se to vubec nepropise do ValidationResult a bud tam probubla error v uplne jinym formatu jinak tam skonci ✅ Host Connection

2024-09-27 11:01 UTC, kudj commented on db_components/db_common/cdc_component.py
>          with self._init_client():
může být takto? přidány ConnectionException a TestConnectionException

2024-09-30 08:05 UTC, davidesner commented
@kudj testy v platforme moi porad neprochazeji https://app.datadoghq.eu/logs?query=%40exceptionId%3Aexception-f32a7e993af0a1d45e7d095f9d8b4f5f%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZJB9P3zzJKEjQAAAAAAAAAYAAAAAEFaSkI5UUxxQUFCSTVoU3JoT3VOY3dKOAAAACQAAAAAMDE5MjQxZjUtMjQxMS00YTU1LWJmZTQtNGM1YmJhNGVmMzFh&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1727682542985&to_ts=1727683442985&live=true

2024-09-30 08:19 UTC, davidesner commented
@kudj moje testy:

**Error konci jako success:**
![image](https://github.com/user-attachments/assets/713648e3-264f-4b12-b638-8cad365844de)
Je to proto, ze to posila jako status:success (viz nas thread v UI slacku)
![image](https://github.com/user-attachments/assets/fff215eb-f4ad-413d-9bbd-99f6c85a23c5)


**Odrazky se spatne renderujou**
![image](https://github.com/user-attachments/assets/c55237d6-222a-457e-862a-a0903a638409)
je to proto,ze tam chybi mezera za `-`

**Warning nema link na docs**
I do warning (jako nahore) bych dal link na docs a tohle

````

To fix the user permissions make sure the use is granted following privileges:

```sql
GRANT
SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT
ON *.* TO 'user' IDENTIFIED BY 'password';
```

For more information, see
the [documentation](https://help.keboola.com/components/extractors/database/mysql/#setting-up-mysql).
````

**Test connection se spatnymy credentials nekdy konci s app error**
https://app.datadoghq.eu/logs?query=%40exceptionId%3Aexception-4f0269dc6f218cde82ec9a141f3ecb7f%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZJCAXrOwoSewgAAAAAAAAAYAAAAAEFaSkNBWTA4QUFBSnAxWnF0VlJjZndBQQAAACQAAAAAMDE5MjQyMDEtYmIyMy00ZDYwLTg5ZTAtZWQzMGNmODE2MGNk&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1727682542985&to_ts=1727683442985&live=true

![image](https://github.com/user-attachments/assets/5f8af814-c21e-4129-a2b9-72d9d0578a2b)

https://connection.eu-central-1.keboola.com/admin/projects/4079/branch/12839/components/kds-team.ex-mysql-cdc/744882425

2024-09-30 08:25 UTC, davidesner requested changes
Tohle https://github.com/keboola/python-cdc-component/pull/97#issuecomment-2382425618

+ chybi uprava schema v Postgres

2024-09-30 08:25 UTC, davidesner commented on db_components/ex_mysql_cdc/component_config/configSchema.json
> +        "validation_button": {
Tady jeste prosim neprejmenovavat ten element. Neni pro to duvod a jen to zpusobi zmatky.

2024-10-01 07:55 UTC, kudj commented
@davidesner opraveno, otestováno

2024-10-01 12:24 UTC, merged